#include "variant.h"
#include "wiring_constants.h"
#include "wiring_digital.h"
#include "nrf.h"

#ifndef NRF_GPIO_PIN_MAP
#define NRF_GPIO_PIN_MAP(port, pin) (((port) << 5) | ((pin) & 0x1F))
#endif

const uint32_t g_ADigitalPinMap[] = {
    NRF_GPIO_PIN_MAP(0, 0),  NRF_GPIO_PIN_MAP(0, 1),  NRF_GPIO_PIN_MAP(0, 2),  NRF_GPIO_PIN_MAP(0, 3),
    NRF_GPIO_PIN_MAP(0, 4),  NRF_GPIO_PIN_MAP(0, 5),  NRF_GPIO_PIN_MAP(0, 6),  NRF_GPIO_PIN_MAP(0, 7),
    NRF_GPIO_PIN_MAP(0, 8),  NRF_GPIO_PIN_MAP(0, 9),  NRF_GPIO_PIN_MAP(0, 10), NRF_GPIO_PIN_MAP(0, 11),
    NRF_GPIO_PIN_MAP(0, 12), NRF_GPIO_PIN_MAP(0, 13), NRF_GPIO_PIN_MAP(0, 14), NRF_GPIO_PIN_MAP(0, 15),
    NRF_GPIO_PIN_MAP(0, 16), NRF_GPIO_PIN_MAP(0, 17), NRF_GPIO_PIN_MAP(0, 18), NRF_GPIO_PIN_MAP(0, 19),
    NRF_GPIO_PIN_MAP(0, 20), NRF_GPIO_PIN_MAP(0, 21), NRF_GPIO_PIN_MAP(0, 22), NRF_GPIO_PIN_MAP(0, 23),
    NRF_GPIO_PIN_MAP(0, 24), NRF_GPIO_PIN_MAP(0, 25), NRF_GPIO_PIN_MAP(0, 26), NRF_GPIO_PIN_MAP(0, 27),
    NRF_GPIO_PIN_MAP(0, 28), NRF_GPIO_PIN_MAP(0, 29), NRF_GPIO_PIN_MAP(0, 30), NRF_GPIO_PIN_MAP(0, 31),
    NRF_GPIO_PIN_MAP(1, 0),  NRF_GPIO_PIN_MAP(1, 1),  NRF_GPIO_PIN_MAP(1, 2),  NRF_GPIO_PIN_MAP(1, 3),
    NRF_GPIO_PIN_MAP(1, 4),  NRF_GPIO_PIN_MAP(1, 5),  NRF_GPIO_PIN_MAP(1, 6),  NRF_GPIO_PIN_MAP(1, 7),
    NRF_GPIO_PIN_MAP(1, 8),  NRF_GPIO_PIN_MAP(1, 9),  NRF_GPIO_PIN_MAP(1, 10), NRF_GPIO_PIN_MAP(1, 11),
    NRF_GPIO_PIN_MAP(1, 12), NRF_GPIO_PIN_MAP(1, 13), NRF_GPIO_PIN_MAP(1, 14), NRF_GPIO_PIN_MAP(1, 15),
};

void initVariant() {}
