name: riftlink_app
description: RiftLink (RL) — приложение для mesh-сети (Heltec LoRa). Android, iOS, Web/PWA.
publish_to: none
version: 1.5.27+13

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue_plus: ^1.31.0
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_sound: ^9.30.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  package_info_plus: ^8.0.0
  file_picker: ^8.0.0
  crypto: ^3.0.0
  flutter_local_notifications: ^17.2.3
  multicast_dns: ^0.3.3
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
